# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random sample from Dirichlet distribution with n = 1.
#'
#' @param alpha The
#'
#' @author David Gerard
#'
#' @noRd
rdirichlet1 <- function(alpha) {
    .Call(`_hwep_rdirichlet1`, alpha)
}

#' Sample gamete counts from full conditional.
#'
#' @param x A vector of genotype counts. x[i] is the number of individuals
#'     with dosage i.
#' @param p A vector of gamete probabilities. p[i] is the proportion of
#'     gametes with dosage i.
#'
#' @author David Gerard
#'
#' @noRd
samp_gametes <- function(x, p) {
    .Call(`_hwep_samp_gametes`, x, p)
}

