# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample gamete counts from full conditional.
#'
#' @param x A vector of genotype counts. x[i] is the number of individuals
#'     with dosage i.
#' @param p A vector of gamete probabilities. p[i] is the proportion of
#'     gametes with dosage i.
#'
#' @author David Gerard
#'
#' @noRd
samp_gametes <- function(x, p) {
    .Call(`_hwep_samp_gametes`, x, p)
}

#' Gibbs sampler under random mating with known genotypes.
#'
#' @param x The vector of genotype counts. x(i) is the number of
#'     individuals that have genotype i.
#' @param alpha Vector of hyperparameters for the gamete frequencies.
#'     Should be length (x.length() - 1) / 2 + 1.
#' @param B The number of sampling iterations.
#' @param T The number of burn-in iterations.
#' @param more A logical. Should we also return posterior draws (\code{TRUE})
#'     or not (\code{FALSE}).
#'
#' @author David Gerard
#'
#' @noRd
gibbs_known <- function(x, alpha, B, T, more) {
    .Call(`_hwep_gibbs_known`, x, alpha, B, T, more)
}

#' Random sample from Dirichlet distribution with n = 1.
#'
#' @param alpha The
#'
#' @author David Gerard
#'
#' @noRd
rdirichlet1 <- function(alpha) {
    .Call(`_hwep_rdirichlet1`, alpha)
}

#' Multinomial probability mass function
#'
#' @param x The counts.
#' @param p The probabilities.
#' @param lg A logical. Should we return log (true) or not (false).
#'
#' @noRd
#' @author David Gerard
dmultinom_cpp <- function(x, p, lg = FALSE) {
    .Call(`_hwep_dmultinom_cpp`, x, p, lg)
}

#' Log-sum-exponential trick using just two doubles.
#'
#' @param x A double.
#' @param y Another double.
#'
#' @return The log of the sum of the exponential of x and y.
#'
#' @author David Gerard
#'
#' @noRd
log_sum_exp_2_cpp <- function(x, y) {
    .Call(`_hwep_log_sum_exp_2_cpp`, x, y)
}

#' Log-sum-exponential trick.
#'
#' @param x A vector to log-sum-exp.
#'
#' @return The log of the sum of the exponential
#'     of the elements in \code{x}.
#'
#' @author David Gerard
#'
#' @noRd
log_sum_exp_cpp <- function(x) {
    .Call(`_hwep_log_sum_exp_cpp`, x)
}

#' Basic convolution using naive algorithm
#'
#' Same as stats::conv(x, rev(y), type = "open"), but using the naive
#' algorithm. This should be faster for very small vectors (but will
#' be horrible for larger vectors).
#'
#' @param x The first vector
#' @param y The second vector
#'
#' @author David Gerard
#'
#' @noRd
conv_cpp <- function(x, y) {
    .Call(`_hwep_conv_cpp`, x, y)
}

